BlueMoon-Labs/Redmoon-Keep

code/__HELPERS/roundend.dm
code/modules/mob/dead/new_player/new_player.dm
modular_redmoon/modules/stats_reports_with_gender_list/stats_reports_with_gender_lists.dm
roguetown.dme

В статистику раунда добавлен подсчёт:
- Количества мужчин, который зашли в раунд
- Количества женщин, которые зашли в раунд
- Количества мужчин с женским началом, которые зашли в раунд
- Количества женщин с мужским началом, которые зашли в раунд
Больше статистики. Это интересная информация.
Помимо того, некоторым людям интересны эти соотношения.

Round End Statistics, genitals edition

---

code/game/objects/items/rogueitems/natural/wood.dm

Squashing a bug whereby you can get an infinite tree flow. 
Small Log > Use Axe (Chop) > We get three sticks > Use Handsaw (Saw) > We get one stake for each stick > Axe or Handsaw (Chop) > We get two (or three if good luck) Small Logs. Infinity is in walking distance.
UP RIGHT DOWN DOWN DOWN

Bugfix Infinity Tree

---

code/datums/mind.dm

Чиним русский язык в memories

---

code/modules/roguetown/roguejobs/cook/tools/milling.dm

1. Пофикшено описание. Теперь он не вечно пустой.
2. Больше нельзя засунуть то, что не будет перемалываться
Фиксы. На основу бы вообще

Фиксы для millstone

---

code/datums/gods/patrons/divine_pantheon.dm

Добавил Orison всем, кто может использовать чудеса из divine_pantheon
Если уже взяли с азурки - это самое простое и первое чудо, которое дается даже самым мелким последователям религии. Оно у нас сейчас ТОЛЬКО у главы цервки (Приста)

Орисон для всех чудесников

---

code/modules/jobs/job_types/roguetown/courtier/butler.dm
code/modules/jobs/jobs.dm

Это упомянутый мною фикс окна выбора придворных в joinlate (https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2363). Я заливаю его локально вам, пока оффы думают. При мерже идентичных участков кода, не должно возникать конфликтов, а я не думаю, что у оффов есть причины НЕ принимать мой фикс.

Joinlate courtiers fix

---

code/game/objects/items/rogueweapons/ranged/bows.dm

Фикс рантайма, не дающего мобам с оружием дальнего боя стрелять

---

modular_redmoon/code/datums/loadout.dm

Просто красивый плащик для лодаута
Вариативность

Дождевой плащик для Лодаута

---

code/modules/spells/roguetown/acolyte/abyssor.dm
code/modules/spells/roguetown/acolyte/general.dm

Сделал меньшему лечению небольшой реген
Немного уменьшил стоимость лечения абиссора (50 слишком много для нашей системы без пассивного регена девоушна)
Пытаюсь приблизить штуки из Азурки к тому что на Азурке

AzurePeak-овое меньшее леченее. Микробафф спец-хила Абиссора

---

code/modules/jobs/job_types/roguetown/church/monk.dm

Xylix acolyte boots fix

---

code/modules/antagonists/roguetown/villain/vampirelord.dm

Фикс количества витэ

---

modular_redmoon/modules/brigandinerebalance/anvil_recipes/armor.dm
modular_redmoon/modules/brigandinerebalance/armor/armor.dm
roguetown.dme

Бригантины модулярные я переделяль

---

modular_redmoon/modules/gatemasterhaskeys/gatemasterkey.dm

Привратник получает ключ от ворот.

---

modular_redmoon/modules/inquisition_overseers/code/jobs/puritan.dm

Угадайте кто дал нормальный рунлок инквизитору но не смотрителю? Я.

---

code/datums/elements/mob_overlay_effect.dm

Чинит ноги персонажа в снегу.
Багофиксы.

REDMOON SNOW LEGS FIX

---

code/modules/mob/living/carbon/life.dm

Топик 
Спать со шлемом на поясе

Разрешаем персонажам спать со шлемом на поясе

---

modular_redmoon/code/game/objects/items/rogueitems/kitchen.dm

Единственный доступный энтент был use, который не имеет возможности навредить другим мобам и структурам. Наследует от kitchen возможность раскатывать тесто, и обретает свойствами оружия. Полезно в импровизированной потасовке. Не уверен насчет модулярной еды, т.к. пологаю именно из-за нее скалка не имеет функции вреда.
Возвращение утерянного функционала.

У скалки не было возможности атаки.

---

code/modules/antagonists/roguetown/villain/vampire.dm
code/modules/antagonists/roguetown/villain/vampirelord.dm

Фиксы
Два раза выдались спеллы, так как два раза выдавал роль спавна на разные классы

Фикс спавна голых миньонов вампиров, bad client

---

modular_redmoon/modules/jobs/job_types/roguetown/church/confessor.dm
modular_redmoon/modules/jobs/job_types/roguetown/church/puritan.dm
modular_redmoon/modules/jobs/job_types/roguetown/courtier/butler.dm
modular_redmoon/modules/jobs/job_types/roguetown/courtier/jester.dm
modular_redmoon/modules/jobs/job_types/roguetown/goblin/goblinrabble.dm
modular_redmoon/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
modular_redmoon/modules/jobs/job_types/roguetown/towners/types/seamster.dm

Фиксы H.mind для классов, чтобы болванка в меню создания персонажа не… пыталась получить навыки и трейты.
Фиксы
---

H.mind для классов,

---

code/modules/mob/dead/new_player/login.dm
code/modules/surgery/bodyparts/bodypart_wounds.dm

Повышение максимального количества сообщений в чате до 800 сообщений

---

code/modules/jobs/job_types/roguetown/mercenaries/types/desertrider.dm

Смайли мне скинул статы старого дезерт-райдера, так что я подогнал их под один из подклассов.
Ну и кастер оказался буквально слишком тупым для игры, так что вернул ему навык чтения, но на 2 уровень.

blade_dancer_stats_balance

---

modular_redmoon/modules/baotha_steals_triumphs/baotha_steals_triumphs.dm

В шапке
https://discord.com/channels/1325992381899866183/1345777829610262579
-

Предложение о конверте в учение Баоты теперь даётся постоянно

---

code/datums/sexcon/sexcon.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf_spells.dm
code/modules/mob/living/carbon/human/examine.dm
modular_redmoon/code/game/objects/items/rogueitems/flail.dm
modular_redmoon/modules/inquisition_overseers/code/clothing.dm

Здесь будет много всяких фиксов из текстовых файлов с логами.

Фиксы рантаймов

---

code/modules/antagonists/roguetown/villain/vampirelord.dm
roguetown.dme

Нужно в тест-мерджу. Ищем причину, почему иногда при выборе классе не даёт выбор подкласса для вампиров.
Фиксим баги
---

Трабл-шутинг спавна вампиров

---

code/datums/migrants/migrant_waves/slaver roles.dm

Чутка изменил пулл рас для Зибантийских рабовладельцев.

Zybantian_slaver_races

---

modular_redmoon/code/datums/loadout.dm

Меня попросили добавить в лодаут кожаный ошейник с колокольчиком.
Я добавил.

loadout_collar_with_bell

---

modular_redmoon/code/datums/status_effects/rogue/debuff.dm
modular_redmoon/code/datums/status_effects/roguestatus.dm

https://discord.com/channels/1325992381899866183/1352981520037445632
-

Уменьшение эффекта на статы от дебафов

---

code/datums/outfit.dm
modular_redmoon/modules/stat_roundstart/stat_roundstart.dm

Исправление ошибки, когда модификаторы статов (например от жажды) на …моменте выбора профессии могут стать раундстартовыми
Фиксы
++

Фикс статов

---

code/game/objects/structures/fluff.dm
code/modules/client/preferences.dm
code/modules/mob/dead/new_player/new_player.dm
modular_redmoon/modules/memory_for_family_members/memory_for_family_members.dm

Фамилия нового члена семьи берётся от изначального после лейтжоина, сохранение Детальной Семьи

---

code/__HELPERS/roundend.dm
modular_redmoon/code/modules/tgs/roundspoke.dm
modular_redmoon/modules/stats_reports_with_gender_list/stats_reports_with_gender_lists.dm

Добавление Краукали в статистику конца раунда

---

modular_redmoon/modules/jobs/job_types/roguetown/mercenaries/types/grenzelhoft.dm
modular_redmoon/modules/jobs/job_types/roguetown/mercenaries/types/grenzelhoft_kommandant.dm
modular_redmoon/modules/jobs/job_types/roguetown/mercenaries/types/grenzelholf_jager.dm
modular_redmoon/modules/jobs/job_types/roguetown/mercenaries/types/newmoon.dm
roguetown.dme

Исправление цвета особых органов у грензельхофцев и ньюмунцев (наёмников)

---

code/controllers/subsystem/ai_controller.dm

Шапка
Фиксы
Гомункул раньше ходил сам и атаковал всех вокруг

Исправление контроля ИИ, когда в мобе уже находится игрок

---

code/modules/mob/dead/new_player/new_player.dm

Исправление стазиса на оборотнях

---

code/game/objects/structures/roguewindow.dm

Через открытые окна теперь можно прыгать и бросать предметы.
Фиксы

Фикс прыжков через открытые окна

---

code/modules/spells/roguetown/wizard.dm
modular_redmoon/code/modules/spells/roguetown/wizard.dm

Исправление отсутствия стоимости у абилки blindness воинов Нок

---

code/modules/mob/living/carbon/carbon.dm

В шапке
https://discord.com/channels/1325992381899866183/1364949195659939961
https://discord.com/channels/1325992381899866183/1364949195659939961

15 силы достаточно для разрывания оков

---

code/game/say.dm
code/modules/mapping/space_management/multiz_helpers.dm
code/modules/mob/living/say.dm

Порт слышимости на multi-Z с Azure-Peak

---

modular_redmoon/modules/translation/obj/structure/fluff.dm
modular_redmoon/modules/translation/obj/structure/roguemachine.dm
modular_redmoon/modules/translation/obj/structure/table.dm

Пока не находится в компиляции.

Пресеты перевода для других разработчиков (мерджить)

---

code/modules/mob/mob.dm

В шапке
https://discord.com/channels/1325992381899866183/1366461300795904131

Убираем голод и жажду раундстартом (можно в ТМ)

---

code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm

В шапке
Множество изменений в файле - так как обезьянка на разработчике изначально вместо табуляций в файле использовала пробелы.
https://discord.com/channels/1325992381899866183/1366141669258563624
https://discord.com/channels/1325992381899866183/1366141669258563624

Оборотень обращается обратно только если видит солнце или находится вне пещер болот (можно в ТМ)

---

code/controllers/subsystem/rogue/family.dm

Должно убрать баг, когда у мужа и жены разные фамилии
фиксы

Мелкофикс для семьи (можно мерджить)

---

roguetown.dme

Случайно выкатили перевод раньше времени.

---

modular_redmoon/modules/translation/obj/item/food.dm

food.dm - переведен на русский язык
Перевод билда на русский язык.

Перевод билда

---

modular_redmoon/code/controllers/subsystem/rogue/triumphs/triumph_buy_datums/antags.dm

В соответствии с предложкой.
Если на сервере менее 40 игроков, антаг-коины, кроме подарка, не работают и деньги за них возвращаются.
https://discord.com/channels/1325992381899866183/1368631612484489356

Минимальное количество для активации антаг-коинов - 40

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

Теперь принц и рыцарь считаются нобелем с начала раунда (и не женятся на простолюдинах) (ТМ)

---

code/modules/admin/player_panel.dm
code/modules/admin/topic.dm
modular_redmoon/modules/old_player_panel/old_player_panel.dm
roguetown.dme

У педалей теперь есть кнопка для вызова старой Player Panel, пока авторы новой не починят крутую.
Фиксы

Добавляем старую игровую панель

---

modular_redmoon/modules/mob/living/carbon/human/species_types/roguetown/halfelf.dm

Добавление эльфийских ушей полуэльфам.
https://discord.com/channels/1325992381899866183/1368918059737157702

Эльфийские ушки полуэльфам
