BlueMoon-Labs/Redmoon-Keep

code/modules/roguetown/roguecrafting/turfs.dm

Позволяет снова крафтить деревянные платформы
Fix

Fix for wooden platforms

---

modular_redmoon/modules/acolytes_can_coronate/acolytes_can_coronate.dm
roguetown.dme

Аколиты могот короновать, как прист, но с условиями.
1. Необходимо, чтобы предыдущий лорд был мёртв.
2. Короновать возможно только наследника или наследницу.
3. В раунд не должен был заходить жрец.
Если жрец был, монарх жив или пытаются короновать бомжа, коронация не пройдёт.
У нас часто нет приста и барона в раунде. Это угнетает, т.к. остаток раунда превращается в тим дезматч против гоблинов.

Возможность короновать для аколитов

---

code/datums/character_flaw/_character_flaw.dm
code/datums/sexcon/sexcon.dm
code/modules/mob/living/carbon/human/examine.dm
modular_redmoon/modules/lovefiend_returns/love_fiend_returns.dm
roguetown.dme

Возвращён перк Lovefind, но переделан.
Вместо необходимости просто достигнуть пика, необходимо сделать это вместе с кем-то, кто будет согласен на любовь.
В теории, это должно защитить от Rape Hobo, которые берут бандитов/стражников/другую силовую роль/бомжей, которые берут силовую роль, чтобы иметь валид украсть селянку для нон-кона.
Больше квирков - богу квирков.
По сути, простые проверки.

Lovefiend, round 2

---

code/modules/mob/living/carbon/carbon.dm

Если проводить хирургическую операцию на этапе с открытой костью ИЛИ ДРАТЬСЯ СО СКЕЛЕТОМ БЕЗ БОЕВОГО РЕЖИМА, открывается панелька операции. Сбрасывая операции (на груди в частности или шее), наносишь удары без КД.
Фиксим баги боевки.

Surgery No Cooldown Strikes Fix

---

modular_redmoon/modules/cloak_hoods_fix/cloak_hoods_fix.dm
roguetown.dme

Если капюшон плаща drag-drop'ом поместить в собственный плащ, то он превратится в 2 клетки, перекрывая обзор. Не чинится ингейм.
Маленький запрет на снятие не через ПКМ по плащу убирает такую проблему.
Фиксы

Фикс капюшона плащей, который превращается в 2 клетки

---

code/modules/client/preferences.dm

Лёгкое изменение строчки Non-Con в настройках куклы: в русском варианте изменено на "Давать отпор".
В формулировке Be Defiant (Быть сопротивляющимся) YES означал сопротивление нонкону и NO - смирение при изнасиловании. Из-за этого люди были в непонятках, что именно оно означает, ибо Non-Con: Yes выдавал в чат подсказку, что кукла будет отбиваться в комбат моде. И Non-Con: No давал текст, что кукла будет смиряться.
Теперь оно будет более интуитивно и согласованно по конструкции "название --> подсказка".

Non-con изменён

---

code/modules/mob/living/carbon/human/species.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorphsmall.dm
code/modules/mob/living/carbon/human/species_types/furry/axian.dm
code/modules/mob/living/carbon/human/species_types/furry/dracon.dm
code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
code/modules/mob/living/carbon/human/species_types/furry/lupian.dm
code/modules/mob/living/carbon/human/species_types/furry/moth.dm
code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm
code/modules/mob/living/carbon/human/species_types/roguetown/goblin/goblinp.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm

1. Гениталии больше не форсируются не персонажа, если они не выставлены в кастомизации.
2. Технически, это даёт создать персонажа вовсе без половых органов ИЛИ только с половыми органами другого пола.
3. Пояснительную лоровую бригаду сюда.
4. Алсо, у ~~дренеек~~ появилась каноничная опция по выбору елды.
Кастомизация.

Убирание форсирования гениталий

---

modular_redmoon/modules/lovefiend_returns/love_fiend_returns.dm

Фикс рантайма, из-за которого проверку на lovefiend незапланированно вызывало на тех, у кого её быть не должно
Фиксы

Фикс проверки на любовника

---

code/controllers/subsystem/rogue/devotion.dm
code/datums/gods/patrons/divine_pantheon.dm

У приста от patron.t0 ломался var/newspell = new spell_type из-за вызова массива (да и у Астраты нету т0), из-за чего не давались спелы вовсе
У Пестранцев единственных не давался Орисон ибо у них свой т0
фиксы

Орисон Пестранцам, "фикс" проблемы вызова пристом массива

---

code/modules/antagonists/roguetown/villain/vampirelord.dm

Чинит классы вампиров, возвращая старые и добавляя вариации новых.

---

code/__HELPERS/roundend.dm
modular_redmoon/code/modules/tgs/roundspoke.dm
modular_redmoon/modules/baotha_steals_triumphs/baotha_steals_triumphs.dm
modular_redmoon/modules/stats_reports_with_gender_list/stats_reports_with_gender_lists.dm

Добавлена статистика рас для конца раунда и IRC.
Изначально хотел сделать через массив, но в таком случае там каждый раз рандомился бы.
Алсо, мимоходом переведена статистика конца раунда в целом.
Люди любят цифры. А разработчики на статистику ориентируются.

Статистика рас для конца раунда

---

modular_redmoon/modules/artificerandguns/runelockrecpies.dm
modular_redmoon/modules/brigandinerebalance/armor/armor.dm
modular_redmoon/modules/microfixes/microfixes.dm
roguetown.dme

Фикс классов брони у частей бригантины легкой
Бригантина защищает лучше чем свой легкий вариант
Наплечники полуброни перестали быть призрачными и защищают руки
Зелье приворота, дилдо, мелок имеют нормальный размер.
Улучшенная фляжка инженерка теперь снова имеет текстуру

Микрофиксы

---

code/modules/jobs/job_types/roguetown/mercenaries/types/newmoon.dm

Наемник Нока получает вместо 1 стартового очка для прокачки 8.
Why?
У чела:
1. Новичок чтения (он читает по слогам, это меньше чем у горожан).
2. Apprentice в аркане (следующая ступень после новичка) в аркане.
3. Худшая для прокачки книга на старте, которую может при желании собрать попрошайка из канавы, взяв светящийся камень
Чтобы начать качаться, ему нужно пройти целый квест и найти редкие предметы, используя шахтёров... И спустя примерно полтора часа, он сможет позволить себе 2 заклинания стартовых.
Я очень не люблю гринд и не хотел бы, чтобы игроки им занимались вместо участия в событиях раунда и взаимодействии.
Spellblade как играбельный класс наемника без гринда в магию, которым занимаются остальные маги.

Бафф New Moon Spellblade

---

code/modules/jobs/job_types/roguetown/mercenaries/types/desertrider.dm

Подребалансил подклассы Дезерт-райдеров. Было ощущение, что при порте с Азуры (вроде), были словно перепутаны навыки.
А так же сделал класс танцора с саблями чуть тупее и чуть медленее, но дал им чуть силы, стараясь выдержать старый баланс, где пустынные наёмники ВСЁ ЕЩЁ должны быть слабее Грензелей, которые по канону всё же являются самой элитной отраслью среди наёмников.
Изменил лодауты, которые так же по ощущению были перепутаны. в итоге
2 сабли, которые были у мага - находятся у блейд денсера.
Хлыст и кинжал парирующий, которые были у блейд денсера - находятся у подкласса мага, так же изменил ему навыки, делая хуже владение мечами, но давая навык на хлысты.
Класс мужика с булавой не затронул, там всё и так ровно выглядело.

desert_rider_classes_rebalance

---

code/modules/jobs/job_types/roguetown/mercenaries/types/desertrider.dm

Ещё чуть-чуть подбалансировал подкласс Блейдкастера у пустынных наёмников.
Во первых дал ему выбор между саблей и кнутом (который я проебал по дурости).
Во вторых убрал у него чтение, т.к. новую магию он не изучит энивей.
В третьих +1 атлетика и +1 лечение.
В четвёртых изменил заклинание на отталкивание, на заклинание цепной молнии, поскольку я не играю на магах и не разбираюсь в этом, человек, который успел уже побегать на этом классе, аргументированно объяснил и показал, почему это стоит менять. Заклинания стоят одинаково по очкам.

Desert rider bladecaster rebalance

---

code/datums/character_flaw/_character_flaw.dm

Фикс для сохранения статов мигрантов после изъяна плохого зрения

---

code/game/objects/items/rogueweapons/rmb_intents.dm

1. Теперь пишется причина провала финта
2. Добавлен перевод
3. Провал финта и попадание в него отображаются в цветах, отличных от цвета, в котором отображаются обычные логи боя.
Финт неочевидная механика. Это поможет игрокам лучше понимать принцип их работы.

Повышение информативности финтов

---

code/controllers/subsystem/rogue/treasury.dm
code/modules/farming/bin.dm
modular_redmoon/modules/prices_fix/prices_fix.dm
modular_redmoon/modules/prices_fix/prices_fix_recipes.dm
roguetown.dme

- Добавлена цена на практически всё оружие.  Она ниже цены производства. 
- Но, оружие, которое куёт кузнец, как минимум окупает цену своего производства для возможности нормальной продажи торговцу. Стальное и золотое лучше.
- В этом же ПР торговый налог гильдии снижен.
https://discord.com/channels/1325992381899866183/1359157625002000476
-

Исправление цен на оружие раундстартом

---

code/modules/antagonists/roguetown/villain/zomble.dm

Удаление датума зомби не вызывает on_removal, что ломает возвращение скиллов. Этот ПР фиксит момент.
Фиксы

Фикс жёсткого удаления зомби

---

code/game/atoms_movable.dm
modular_redmoon/modules/unbreakable_castle_underwalls/unbreakable_castle_underwalls.dm
roguetown.dme

- Стена в основании замка больше не может быть пробита обычными средствами (например, киркой).
- Персонажи больше не могут прыгать дальше, чем то задумано игрой (там происходило перемножение ускорения на дальность).
Фиксим баги.
Подкопы - рак.
-

Фикс прыжка на 6 тайлов, добавление непробиваемой обычными средствами стены в основание замка

---

code/modules/spells/roguetown/wizard.dm

Заклинание blade burst самоудалялось при касте по существу, обладающему иммунитетом к антимагии.
Фиксы

Исправление самоудаления заклинания blade burst

---

code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
modular_redmoon/modules/scomrings/rings/startthings.dm

- При рекрутировании авангарда, не писалась новая должность у призывника. Исправлено.
- Из-за неправильной постановки ..(), id при выдаче ском-колец переписывался. Исправлено.
фиксы
-

Исправление выдачи ском-колец многим ролям и рекрутинга авангарда

---

code/__HELPERS/roundend.dm
modular_redmoon/code/modules/tgs/roundspoke.dm

Добавление статистики профессий в экран конца раунда и в отчёт в дискорд.
На основе точной статистики можно делать выводы и более точно изменять игру.
+

Статистика профессий

---

code/__REDFINES/prefereces.dm
code/modules/client/client_procs.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
modular_redmoon/code/modules/client/preferences.dm
modular_redmoon/code/modules/mob/living/overhead_effects.dm
modular_redmoon/modules/client/preferences_savefile.dm
modular_redmoon/modules/commend_comments/commend_comments.dm
roguetown.dme

1. Uncommend и Commend теперь используют разные переменные. Можно хвалить и ругать по одному разу за раунд, а не только хвалить или ругать.
2. Uncommend больше не снимает PQ, но оставляет комментарий, которую видит игрок.
3. Исправлена неправильная запись настроек, от чего некоторые наши префы сохранялись только при сохранении у персонажа и могли некорректно переходить от одного к другому
4. Новый преф, позволяющий убрать звук от эффекта стресса.
https://discord.com/channels/1325992381899866183/1364838826245361665
https://discord.com/channels/1325992381899866183/1364838826245361665

Работа над Uncommend, фикс неправильного сохранения префов и преф на отключение звуков и эффектов стресса

---

code/datums/components/rotting.dm

В шапке.
Предлагали до 8 минут. Сделал до 10. т.к.:
Мне кажется, зомби привносят в игру мало реальных угроз и интереса, и тем не менее, приносят. Поднятие таймера для случаев, когда умерли где-то в населенном месте до подобного значения, позволит куда оперативнее принять меры.
https://discord.com/channels/1325992381899866183/1343564703590387783
https://discord.com/channels/1325992381899866183/1343564703590387783

Время становления зомби увеличено с 4 минут до 10 минут

---

code/__DEFINES/roguetown.dm

Исправляет форс любого из патронов десятки для таких ролей как:
У рефуг:
- Странствующий проповедник
- Рыцарь
- Рыцарь-капитан
- Привратник
- Десятник
Исправляет форс любого из имеющихся в игре божественных патронов для таких ролей, как:
- вагабонд
- ундердвеллеры
- скевенджеры
- роги
- артисты
- ноблы-рефуги
- торговец
- магос-рефуга
- целитель
- дезертир
Фиксы

Исправление, что атеизм автоматически убирался у многих профессий и классов (можно в ТМ)

---

code/modules/client/preferences.dm
modular_redmoon/code/modules/client/preferences.dm
modular_redmoon/modules/client/preferences_savefile.dm
modular_redmoon/modules/jobs/job_types/roguetown/nobility/hand.dm

1. Добавлен возможность зайти за десницу в процессе раунда (только если в раунде уже есть герцог)
2. Добавлена возможность герцогу выставить через новое меню дополнительных настроек то, какого игрока он хочет видеть в качестве своей десницы.
Хоть кому-то герцог должен доверять.

Возвращение set hand

---

code/modules/antagonists/roguetown/villain/vampirelord.dm

1. Лорд вампиров получил легенду во владении оружием.
Возможно, он станет менее лохом (но это не точно). Аргументировано, что челик жил достаточно долго.
2. Пофикшены порталы. Открытие амулета, отправка на амул, возврат с амулета.
3. Исправлено удаление игрока в лобби при попытке становления рыцарем смерти.
Фиксы

Изменения и фиксы для лорда вампиров

---

code/modules/mob/living/blood.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/say.dm

Админы теперь слышат на все з-уровни, если включена опция hear-all
Скорость задыхания в крите снижена.
Кровотечение при очень маленьких порезах убрано. У нас не образуются лужи крови, когда порезался палец.
Кровотечение при очень низком кровяном давлении (при потере более 80% от того, что изначально в теле) теперь прекращает дальнейшее кровотечение, но не закрывает раны. Спасти проще.
Повышение выживаемости
фиксы

Фикс ушей админов. Снижение летальности кровотечений.
